# JVM 参数：2G 堆足够编译本项目，CI 上更稳
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# Gradle 性能与缓存
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false

# Kotlin 官方代码风格
kotlin.code.style=official
